name: Check external repo releases

on:
  schedule:
    - cron: '0 2 * * *'     # every day at 2:00 AM UTC
  workflow_dispatch:        # manual run

env:
  EXTERNAL_OWNER: "mozilla-services"        # <-- change this
  EXTERNAL_REPO: "syncstorage-rs"     # <-- change this
  RELEASE_FILE: "syncstorage-rs-release-version"   # file to store last-seen tag

permissions:
  contents: write
  pull-requests: write

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest release from external repo
        id: latest
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = process.env.EXTERNAL_OWNER;
            const repo = process.env.EXTERNAL_REPO;
            try {
              const r = await github.rest.repos.getLatestRelease({ owner, repo });
              core.setOutput('tag', r.data.tag_name);
              core.setOutput('url', r.data.html_url);
            } catch (err) {
              console.log("No valid release data found.");
              core.setOutput('tag', '');
            }

      - name: Read stored release (if any)
        if: steps.latest.outputs.tag != ''
        id: read
        run: |
          echo "STORED=$(cat $RELEASE_FILE 2>/dev/null || true)" >> $GITHUB_OUTPUT

      - name: Compare and update
        if: steps.latest.outputs.tag != '' && steps.latest.outputs.tag != steps.read.outputs.STORED
        run: |
          echo "${{ steps.latest.outputs.tag }}" > $RELEASE_FILE
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add $RELEASE_FILE
          git commit -m "chore: update ${EXTERNAL_OWNER}/${EXTERNAL_REPO} to ${{ steps.latest.outputs.tag }}" || echo "no changes"

      - name: Create Pull Request
        if: steps.latest.outputs.tag != '' && steps.latest.outputs.tag != steps.read.outputs.STORED
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update ${{ env.EXTERNAL_OWNER}}/${{ env.EXTERNAL_REPO}} to ${{ steps.latest.outputs.tag }}"
          title: "Update ${{ env.EXTERNAL_OWNER}}/${{ env.EXTERNAL_REPO}} to ${{ steps.latest.outputs.tag }}"
          body: |
            Detected new release of ${{ env.EXTERNAL_OWNER}}/${{ env.EXTERNAL_REPO}}: ${{ steps.latest.outputs.tag }}
            ${{ steps.latest.outputs.url }}
          branch: "update-external-release-${{ steps.latest.outputs.tag }}"
